from fpdf import FPDF
from io import BytesIO

class PayslipGenerator(FPDF):
    def header(self):
        # Company Logo/Name
        self.set_font('helvetica', 'B', 20)
        self.set_text_color(99, 102, 241) # var(--primary)
        self.cell(0, 10, 'Payroll DBMS', ln=True, align='L')
        self.set_font('helvetica', '', 10)
        self.set_text_color(100)
        self.cell(0, 5, 'Executive Financial Document', ln=True, align='L')
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('helvetica', 'I', 8)
        self.set_text_color(150)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by Payroll Intelligence System', align='C')

def generate_payslip_pdf(payroll_record):
    pdf = PayslipGenerator()
    pdf.add_page()
    
    # Employee Info Box
    pdf.set_fill_color(248, 250, 252)
    pdf.set_font('helvetica', 'B', 12)
    pdf.cell(0, 10, 'Employee Details', ln=True, fill=True)
    pdf.set_font('helvetica', '', 10)
    pdf.cell(95, 7, f'Name: {payroll_record.user.name}', ln=False)
    pdf.cell(95, 7, f'Email: {payroll_record.user.email}', ln=True)
    pdf.cell(95, 7, f'Month/Year: {payroll_record.month}/{payroll_record.year}', ln=False)
    pdf.cell(95, 7, f'Designation: {payroll_record.user.profile.job_title if payroll_record.user.profile else "N/A"}', ln=True)
    pdf.ln(10)

    # Earnings & Deductions Table
    pdf.set_font('helvetica', 'B', 12)
    pdf.cell(0, 10, 'Salary Breakdown', ln=True, fill=True)
    
    # Header
    pdf.set_font('helvetica', 'B', 10)
    pdf.cell(100, 10, 'Description', border=1)
    pdf.cell(90, 10, 'Amount (USD)', border=1, ln=True, align='R')
    
    # Rows
    pdf.set_font('helvetica', '', 10)
    
    # We fetch salary structure from the profile
    ss = payroll_record.user.profile.salary_structure if payroll_record.user.profile else None
    base = ss.base_salary if ss else 0
    allowances = ss.allowances if ss else 0
    deductions = ss.deductions if ss else 0

    pdf.cell(100, 10, 'Base Salary', border=1)
    pdf.cell(90, 10, f'${base:,.2f}', border=1, ln=True, align='R')
    
    pdf.cell(100, 10, 'Allowances', border=1)
    pdf.cell(90, 10, f'${allowances:,.2f}', border=1, ln=True, align='R')
    
    pdf.set_text_color(244, 63, 94) # Danger color
    pdf.cell(100, 10, 'Deductions', border=1)
    pdf.cell(90, 10, f'-${deductions:,.2f}', border=1, ln=True, align='R')
    
    pdf.set_text_color(0)
    pdf.set_font('helvetica', 'B', 12)
    pdf.cell(100, 12, 'NET PAYABLE', border=1)
    pdf.cell(90, 12, f'${payroll_record.net_amount:,.2f}', border=1, ln=True, align='R')
    
    pdf.ln(20)
    pdf.set_font('helvetica', 'I', 10)
    pdf.multi_cell(0, 5, 'This is a computer-generated document and does not require a physical signature. For any discrepancies, please contact the HR department.')

    return pdf.output()
